wandb_version: 1

beam_width:
  value: 1
cell_type:
  value: gru
dropout:
  value: 0.3
embedding_size:
  value: 128
epochs:
  value: 10
hidden_layer_size:
  value: 64
learning_rate:
  value: 0.01
num_hidden_layers:
  value: 3
optimizer:
  value: SGD
