wandb_version: 1

beam_width:
  value: 1
cell_type:
  value: rnn
dropout:
  value: 0
embedding_size:
  value: 128
epochs:
  value: 10
hidden_layer_size:
  value: 256
learning_rate:
  value: 0.0005
num_hidden_layers:
  value: 1
optimizer:
  value: Adam
