wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.10.6
    start_time: 1683872927.552062
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 17
      - 23
      - 37
      4: 3.10.6
      5: 0.13.11
      8:
      - 1
      - 2
      - 5
beam_width:
  desc: null
  value: 1
cell_type:
  desc: null
  value: gru
dropout:
  desc: null
  value: 0.2
embedding_size:
  desc: null
  value: 64
epochs:
  desc: null
  value: 10
hidden_layer_size:
  desc: null
  value: 128
learning_rate:
  desc: null
  value: 0.005
num_hidden_layers:
  desc: null
  value: 3
optimizer:
  desc: null
  value: SGD
