wandb_version: 1

beam_width:
  value: 1
cell_type:
  value: rnn
dropout:
  value: 0
embedding_size:
  value: 64
epochs:
  value: 2
hidden_layer_size:
  value: 128
learning_rate:
  value: 0.0005
num_hidden_layers:
  value: 2
optimizer:
  value: Adam
