wandb_version: 1

beam_width:
  value: 1
cell_type:
  value: lstm
dropout:
  value: 0.2
embedding_size:
  value: 256
epochs:
  value: 2
hidden_layer_size:
  value: 64
learning_rate:
  value: 0.001
num_hidden_layers:
  value: 3
optimizer:
  value: Adam
